name: Build Fabric Mod

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/.gradle
            .gradle/
            build/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Find and Upload Build Artifact
        run: |
          # Assuming your mod JAR file follows a specific naming pattern
          MOD_JAR=$(ls build/libs/*.jar | grep -E 'LazyDFU-.*\.jar' || true)
          if [ -n "$MOD_JAR" ]; then
            echo "Uploading $MOD_JAR"
            echo "::set-output name=mod_jar::$MOD_JAR"
          else
            echo "No mod JAR file found!"
            exit 1
          fi
        id: find-mod-jar

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: fabric-mod
          path: ${{ steps.find-mod-jar.outputs.mod_jar }}
