name: Build Fabric Mod

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            /home/runner/.gradle
            .gradle/
            build/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Find and Upload Build Artifacts
        run: |
          # Find all .jar files in the build/libs/ folder
          MOD_JARS=$(ls build/libs/*.jar || true)
          if [ -n "$MOD_JARS" ]; then
            for MOD_JAR in $MOD_JARS; do
              echo "Uploading $MOD_JAR"
              # Upload each .jar file by setting the output
              echo "::set-output name=mod_jar::$MOD_JAR"
            done
          else
            echo "No .jar files found!"
            exit 1
          fi
        id: find-mod-jars

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: fabric-mod
          path: ${{ steps.find-mod-jar.outputs.mod_jar }}
